version: "3.3"
services:
  nodejs:
    build:
      context: .
      dockerfile: DockerFile
    image: nodejs
    container_name: e_commerce_app
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_HOSTNAME=mongo_db
      - MONGO_DB=eCommerceDb
      - MONGO_PORT=27017
    ports:
      - "80:8080"
    volumes:
      - /app
      - node_modules:/node_modules
    networks:
      - e_commerce_backend_network
    command: npm run dev

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongo_db_data:/data/db
    networks:
      - e_commerce_backend_network

networks:
  e_commerce_backend_network:
    driver: bridge

volumes:
  mongo_db_data:
  node_modules:
